from models import Team


Russia = Team(name='Russia', rank=65)
Germany = Team(name='Germany', rank=1)
Portugal = Team(name='Portugal', rank=3)
Brazil = Team(name='Brazil', rank=2)
Argentina = Team(name='Argentina', rank=4)
Belgium = Team(name='Belgium', rank=5)
Poland = Team(name='Poland', rank=6)
France = Team(name='France', rank=7)
Spain = Team(name='Spain', rank=8)
Peru = Team(name='Peru', rank=10)
Switzerland = Team(name='Switzerland', rank=11)
England = Team(name='England', rank=12)
Colombia = Team(name='Colombia', rank=13)
Mexico = Team(name='Mexico', rank=16)
Uruguay = Team(name='Uruguay', rank=17)
Croatia = Team(name='Croatia', rank=18)
Denmark = Team(name='Denmark', rank=19)
CostaRica = Team(name='Costa Rica', rank=22)
Iceland = Team(name='Iceland', rank=21)
Sweden = Team(name='Sweden', rank=25)
Tunisia = Team(name='Tunisia', rank=28)
Egypt = Team(name='Egypt', rank=30)
Senegal = Team(name='Senegal', rank=32)
Iran = Team(name='Iran', rank=34)
Serbia = Team(name='Serbia', rank=38)
Nigeria = Team(name='Nigeria', rank=41)
Australia = Team(name='Australia', rank=43)
Japan = Team(name='Japan', rank=44)
Morocco = Team(name='Morocco', rank=48)
Panama = Team(name='Panama', rank=49)
SouthKorea = Team(name='South Korea', rank=62)
SaudiArabia = Team(name='Saudi Arabia', rank=63)

HOST_NATION = Russia
